<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="nextReleaseProblem" nsURI="http://model.nrp" nsPrefix="NRP">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="NRP">
    <eStructuralFeatures xsi:type="ecore:EReference" name="customers" lowerBound="1"
        upperBound="-1" eType="#//Customer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="availableArtifacts" lowerBound="1"
        upperBound="-1" eType="#//SoftwareArtifact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" lowerBound="1"
        upperBound="-1" eType="#//Requirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="solutions" upperBound="-1"
        eType="#//Solution" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="desires" lowerBound="1"
        upperBound="-1" eType="#//ValuedRequirement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cost">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//CostType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareArtifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requires" upperBound="-1"
        eType="#//SoftwareArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="costs" lowerBound="1" upperBound="-1"
        eType="#//Cost" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realisation" lowerBound="1"
        upperBound="-1" eType="#//RequirementRealisation" eOpposite="#//RequirementRealisation/softwareartifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="solutions" upperBound="-1"
        eType="#//Solution" eOpposite="#//Solution/selectedArtifacts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependsOn" upperBound="-1"
        eType="#//Requirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realisation" upperBound="-1"
        eType="#//RequirementRealisation" containment="true" eOpposite="#//RequirementRealisation/requirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valuation" lowerBound="1"
        upperBound="-1" eType="#//ValuedRequirement" containment="true" eOpposite="#//ValuedRequirement/requirement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementRealisation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="requirement.name.concat(' ').concat(let str=((self.percentage*100).round()/100).toString() in str.substring(1, str.indexOf('.')+2))"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement" lowerBound="1"
        eType="#//Requirement" eOpposite="#//Requirement/realisation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="softwareartifact" lowerBound="1"
        upperBound="-1" eType="#//SoftwareArtifact" eOpposite="#//SoftwareArtifact/realisation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Solution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedArtifacts" upperBound="-1"
        eType="#//SoftwareArtifact" eOpposite="#//SoftwareArtifact/solutions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CostType">
    <eLiterals name="MONEY"/>
    <eLiterals name="TIME" value="1"/>
    <eLiterals name="MANPOWER" value="2"/>
    <eLiterals name="RESOURCES" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValuedRequirement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="requirement.name.concat(' ').concat(let str=((self.value*100).round()/100).toString() in str.substring(1, str.indexOf('.')+2))"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement" lowerBound="1"
        eType="#//Requirement" eOpposite="#//Requirement/valuation"/>
  </eClassifiers>
</ecore:EPackage>
